module.exports = {
  setupWizard: {
    "Configure a sua Loja": "title",
    "Complete os passos para ativar o seu estabelecimento na Glamzo.": "subtitle",
    "Informações da Loja": "storeInfo",
    "Imagens do Estabelecimento (Capa e Perfil)": "imagesTitle",
    "Carregar Foto de Capa": "uploadCover",
    "Alterar Capa": "changeCover",
    "Alterar": "change",
    "Clique em \"Alterar Capa\" para o banner superior e passe o rato por cima do círculo central para alterar o seu perfil comercial.": "coverHint",
    "Nome do Estabelecimento *": "storeName",
    "Ex: Barbearia Central": "storeNamePlaceholder",
    "Categoria do Estabelecimento *": "storeCategory",
    "Isso ajuda a interligar e filtrar os seus serviços para que os clientes o encontrem facilmente.": "storeCategoryHint",
    "Telefone *": "phone",
    "Ex: 910 000 000": "phonePlaceholder",
    "E-mail": "email",
    "Ex: ola@barbearia.pt": "emailPlaceholder",
    "Morada *": "address",
    "Ex: Rua Direita": "addressPlaceholder",
    "Nº Porta / Andar": "door",
    "Ex: 12, 1º Esq": "doorPlaceholder",
    "Código Postal *": "postalCode",
    "Ex: 1000-100": "postalCodePlaceholder",
    "Cidade *": "city",
    "Ex: Lisboa": "cityPlaceholder",
    "Distrito *": "district",
    "Ex: Lisboa": "districtPlaceholder",
    "Encontrar no Mapa 📍": "findOnMap",
    "Localização Exata no Mapa *": "exactLocation",
    "Arraste o marcador ou clique no mapa para posicionar o seu estabelecimento com precisão de modo a não haver erro de distância.": "mapHint",
    "Arraste até à sua Loja": "dragToStore",
    "Pré-visualização do Mapa": "mapPreview",
    "Insira a morada correta acima. As coordenadas serão geradas automaticamente ou configuradas no mapa.": "mapAddressHint",
    "Coords:": "coords",
    "Configuração Mágica (Oferta)": "magicSetupTitle",
    "Não quer perder tempo a configurar serviços e horários? Nós tratamos de tudo por si, sem custos adicionais. Preencha apenas os dados acima e clique no botão abaixo.": "magicSetupDesc",
    "Quero que a Glamzo configure a loja para mim": "magicSetupBtn",
    "Horários de Funcionamento": "businessHoursTitle",
    "Defina os dias e horas em que a sua loja está aberta. Isto garante que os clientes apenas podem marcar dentro deste horário.": "businessHoursDesc",
    "até": "until",
    "Fechado": "closed",
    "Serviços": "servicesTitle",
    "min": "min",
    "Serviços Recomendados (": "recommendedServices",
    "Clique para adicionar instantaneamente os serviços mais solicitados:": "addRecommendedHint",
    "Adicionar Serviço": "addServiceBtn",
    "Nome do Serviço": "serviceNamePlaceholder",
    "Selecione o Tipo de Serviço (Opcional)": "serviceTypePlaceholder",
    "Duração (min)": "durationPlaceholder",
    "Preço (€)": "pricePlaceholder",
    "Escolha o seu Plano": "choosePlanTitle",
    "Glamzo PRO": "planPro",
    "/mês": "perMonth",
    "14 Dias Grátis": "free14Days",
    "Agenda e Website SEO": "featureAgendaSeo",
    "Tap-to-Pay no Telemóvel": "featureTapToPay",
    "Zero taxas (Staff Ilimitado)": "featureZeroFees",
    "Recomendado": "recommendedBadge",
    "Terminal Físico Glamzo": "planTerminal",
    "Único": "uniquePayment",
    "Portes e Impostos Incluídos": "featureShippingIncluded",
    "Sem Mensalidades/Fidelização": "featureNoFidelity",
    "Contactless e Chip": "featureContactless",
    "Integração Direta c/ Agenda": "featureDirectIntegration",
    "O terminal é seu para sempre.": "terminalForever",
    "Dados de Envio do Terminal": "shippingDataTitle",
    "Nome Destinatário": "shippingNamePlaceholder",
    "Telefone": "shippingPhonePlaceholder",
    "Morada": "shippingAddressPlaceholder",
    "Código Postal": "shippingPostalCodePlaceholder",
    "Cidade": "shippingCityPlaceholder",
    "Ao avançar, será redirecionado para o Stripe para adicionar o seu cartão e iniciar os seus 14 dias grátis.": "stripeRedirectFree",
    "Ao avançar, será redirecionado para o Stripe para adicionar o seu cartão e concluir a adesão.": "stripeRedirectPay",
    "Voltar": "backBtn",
    "Receber Pagamentos Online": "receiveOnlineTitle",
    "Para aceitar pagamentos com segurança e receber transferências diretamente na sua conta bancária, conecte a sua conta Stripe Connect agora. Pode também saltar este passo e configurar mais tarde.": "receiveOnlineDesc",
    "Configuração Concluída": "setupDoneTitle",
    "A sua conta bancária está associada.": "bankConnected",
    "Prosseguir": "proceedBtn",
    "Conectar Stripe Glamzo Pay": "connectStripeBtn",
    "Configurar mais tarde": "setupLaterBtn",
    "Tudo Pronto!": "allReadyTitle",
    "Dados da Loja": "storeDataStep",
    "Serviços (": "servicesStep",
    "Plano Subscrito": "subscribedPlanStep",
    "Pagamentos Online": "onlinePaymentsStep",
    "Mais tarde": "laterLabel",
    "Concluir Setup & Entrar": "finishSetupBtn",
    
    // Toasts and alerts
    "Confirmado! O seu plano foi subscrito com sucesso.": "errSubscriptionSuccess",
    "O pagamento não foi concluído ou foi cancelado. Por favor, tente novamente ou escolha outro plano.": "errPaymentCancelled",
    "Conta de pagamentos associada com sucesso.": "errStripeConnectSuccess",
    "O processo de configuração de pagamentos foi interrompido.": "errStripeConnectInterrupt",
    "Erro ao preparar a configuração da loja: ": "errSetupPrepare",
    "Preencha os campos obrigatórios.": "errRequiredFields",
    "Adicione pelo menos um serviço para prosseguir.": "errAddOneService",
    "Erro de Validação: Preencha todos os dados de envio do terminal (Nome, Telefone, Morada, Código Postal e Cidade) para continuar.": "errShippingData",
    "Erro no pagamento Stripe: ": "errStripePayment",
    "Preencha os campos obrigatórios (Nome, Telefone, Morada, Código Postal, Cidade, Distrito).": "errRequiredFieldsFull",
    "Erro de Segurança: Não foi encontrada uma subscrição ativa para este espaço. Por favor, assine um plano de subscrição na etapa anterior para que possamos ativar o seu website público.": "errSecuritySub",
    "Erro ao remover serviço: ": "errRemoveService",
    "Erro ao adicionar serviço: ": "errAddService",
    "Preencha todos os campos do serviço": "errFillService",
  },
  agenda: {
    "Agenda": "title",
    "Dia": "day",
    "3 Dias": "threeDays",
    "Semana": "week",
    "Nova": "newBooking",
    "Filtrar": "filterBtn",
    "Ver Todos": "viewAllBtn",
    "Detalhes da Reserva": "bookingDetails",
    "Serviço & Notas": "serviceAndNotes",
    "Hora": "time",
    "Profissional": "professional",
    "Estado do Pagamento": "paymentStatus",
    "✅ Já pagou online": "paidOnline",
    "⚠️ A receber no local": "payLocal",
    "Valor": "value",
    "Confirmar Marcação": "confirmBookingBtn",
    "Serviço Concluído": "serviceCompletedBtn",
    "Cobrar ao Cliente": "chargeClientBtn",
    "Confirmar Conclusão": "confirmCompletionBtn",
    "Cancelar Marcação": "cancelBookingBtn",
    "Abrir Disputa / Problema": "openDisputeBtn",
    "Escolha o método de cobrança para concluir o pagamento na loja.": "chargeClientDesc",
    "Tap-to-Pay (NFC)": "tapToPayBtn",
    "Terminal Físico": "physicalTerminalBtn",
    "Envie o valor para o seu Stripe Reader M2 / WisePad 3 via Bluetooth.": "terminalDesc",
    "Reportar Problema": "reportProblemTitle",
    "Esta ação irá abrir uma queixa formal junto da equipa de Suporte Glamzo.": "reportProblemDesc",
    "Cliente não compareceu (No-show)": "disputeNoShow",
    "Cliente recusou-se a pagar": "disputeRefused",
    "Comportamento inadequado": "disputeBehavior",
    "Outro problema de cobrança": "disputeOther",
    "Detalhe o que aconteceu...": "disputeDetailPlaceholder",
    "Enviar Queixa Oficial": "sendDisputeBtn",
    "Nova Marcação": "newBookingTitle",
    "Cliente": "clientTab",
    "Bloqueio": "blockTab",
    "Nome": "nameLabel",
    "Ex: Maria": "namePlaceholder",
    "Serviço": "serviceLabel",
    "Equipa": "teamLabel",
    "Toda a Equipa": "allTeam",
    "Selecione um funcionário": "selectStaff",
    "Motivo": "reasonLabel",
    "Duração": "durationLabel",
    "15 min": "min15",
    "30 min": "min30",
    "45 min": "min45",
    "1h": "h1",
    "1h 30m": "h1m30",
    "2h": "h2",
    "3h": "h3",
    "4h": "h4",
    "5h": "h5",
    "8h": "h8",
    "Data": "dateLabel",
    "Cancelar": "cancelBtn",

    "Operação cancelada! O teu espaço está fechado nesta data.": "errClosedDate",
    "Operação cancelada! Fora do horário de expediente.": "errOutsideHours",
    "Operação cancelada! Já existe uma marcação ou bloqueio neste horário para o profissional selecionado.": "errOverlap",
    "🛑 Bloqueio Ativado": "succBlockActive",
    "📅 Gravado": "succBookingSaved",
    "Agenda atualizada.": "succAgendaUpdated",
    "Erro ao guardar dados.": "errSaveData",
    "Queixa registada com sucesso. A equipa vai analisar.": "succDisputeRegistered",
    "Erro ao abrir disputa.": "errOpenDispute",
    "✅ Concluída!": "succServiceClosed",
    "Serviço fechado e pontos atribuídos.": "succPointsAssigned",
    "Erro ao atualizar o estado.": "errUpdateStatus",
    "O valor da marcação é 0€": "errBookingValueZero",
    "Pagamento Concluído com Sucesso!": "succPaymentComplete",
    "Erro ao processar pagamento": "errProcessPayment",
  }
};
