import fs from 'fs';
let code = fs.readFileSync('src/emails/GlamzoTemplates.tsx', 'utf8');

const tStart = code.indexOf('const translations: any = {');
const tEnd = code.indexOf('const t = (key: string, lang: string = "pt") => {');

const translationsCode = `const translations: any = {
  pt: {
    bookingConfirmed: "A tua marcação está confirmada!",
    bookingConfirmedTitle: "Marcação Confirmada ✅",
    professional: "Profissional",
    service: "Serviço",
    date: "Data",
    time: "Hora",
    value: "Valor",
    reference: "Referência",
    bookingFooter: "Podes consultar os detalhes e gerir a tua marcação na app.",
    team: "A equipa Glamzo",
    bookingCancelled: "A tua marcação foi cancelada",
    bookingCancelledTitle: "Marcação Cancelada ❌",
    reason: "Motivo",
    cancelledFooter: "Se tiveres dúvidas, entra em contacto com o salão ou agenda um novo horário.",
    newBooking: "Nova marcação na Glamzo",
    newBookingTitle: "Nova Reserva Recebida! 🎉",
    estimatedValue: "Valor Estimado",
    newBookingFooter: "Consulta a tua agenda na plataforma para mais detalhes.",
    subActiveTitle: "Subscrição Ativa 🚀",
    activation: "Ativação",
    nextBilling: "Próxima Cobrança",
    subActiveFooter: "Já tens acesso imediato a todas as funcionalidades avançadas de gestão e marketing.",
    openDashboard: "Abrir Dashboard PRO",
    invoiceAvailable: "Acesso à sua Fatura",
    invoiceBody: "O pagamento da sua subscrição foi processado com sucesso. A fatura já se encontra disponível.",
    invoiceNo: "Nº Fatura",
    amountPaid: "Valor Pago",
    downloadInvoice: "Download da Fatura",
    paymentFailed: "Método de Pagamento Recusado ⚠️",
    updatePayment: "Atualizar Pagamento",
    welcomeStaff: "Bem-vindo à equipa do ",
    staffBody: "A tua conta foi criada com sucesso. Podes aceder ao teu painel de funcionário no Glamzo usando as seguintes credenciais:",
    email: "Email",
    password: "Password",
    ignoreEmail: "Se não esperavas este email, podes ignorar.",
    anyone: "Qualquer um",
    accessDashboard: "Aceder ao Painel",
    verificationCode: "O teu código de verificação",
    welcome: "Bem-vindo(a),",
    thanksForRegistering: "Obrigado por te registares na Glamzo. Para garantirmos a segurança da tua conta e poderes continuar com o registo, introduz o seguinte código de verificação:",
    validCode: "Este código é válido apenas para o processo de registo atual.",
    confirmEmailPreview: "Confirma o teu email na Glamzo",
    confirmEmailBody: "Obrigado por te registares na Glamzo. Para garantirmos a segurança da tua conta e desbloquear todas as funcionalidades, precisamos que confirmes o teu endereço de email.",
    confirmEmailBtn: "Confirmar Email",
    confirmEmailNote: "Nota: Contas não verificadas não podem realizar marcações. Este link tem uma validade limitada.",
    passResetPreview: "Recuperação de Password",
    hello: "Olá",
    passResetBody: "Recebemos um pedido para repor a password da tua conta Glamzo. Se foste tu, clica no botão abaixo para criar uma nova password:",
    passResetBtn: "Repor Password",
    passResetNote: "Se não fizeste este pedido, podes ignorar este email com segurança. O link expira em 24 horas."
  },
  en: {
    bookingConfirmed: "Your booking is confirmed!",
    bookingConfirmedTitle: "Booking Confirmed ✅",
    professional: "Professional",
    service: "Service",
    date: "Date",
    time: "Time",
    value: "Price",
    reference: "Reference",
    bookingFooter: "You can view the details and manage your booking in the app.",
    team: "The Glamzo Team",
    bookingCancelled: "Your booking was cancelled",
    bookingCancelledTitle: "Booking Cancelled ❌",
    reason: "Reason",
    cancelledFooter: "If you have any questions, contact the salon or book a new time.",
    newBooking: "New booking on Glamzo",
    newBookingTitle: "New Booking Received! 🎉",
    estimatedValue: "Estimated Price",
    newBookingFooter: "Check your calendar on the platform for more details.",
    subActiveTitle: "Subscription Active 🚀",
    activation: "Activation",
    nextBilling: "Next Billing",
    subActiveFooter: "You now have immediate access to all advanced management and marketing features.",
    openDashboard: "Open PRO Dashboard",
    invoiceAvailable: "Access your Invoice",
    invoiceBody: "Your subscription payment was processed successfully. The invoice is now available.",
    invoiceNo: "Invoice No.",
    amountPaid: "Amount Paid",
    downloadInvoice: "Download Invoice",
    paymentFailed: "Payment Method Declined ⚠️",
    updatePayment: "Update Payment",
    welcomeStaff: "Welcome to the team at ",
    staffBody: "Your account has been successfully created. You can access your staff dashboard on Glamzo using the following credentials:",
    email: "Email",
    password: "Password",
    ignoreEmail: "If you didn't expect this email, you can ignore it.",
    anyone: "Anyone",
    accessDashboard: "Access Dashboard",
    verificationCode: "Your verification code",
    welcome: "Welcome,",
    thanksForRegistering: "Thank you for registering with Glamzo. To ensure the security of your account and continue with registration, please enter the following verification code:",
    validCode: "This code is only valid for the current registration process.",
    confirmEmailPreview: "Confirm your email on Glamzo",
    confirmEmailBody: "Thank you for registering with Glamzo. To ensure the security of your account and unlock all features, we need you to confirm your email address.",
    confirmEmailBtn: "Confirm Email",
    confirmEmailNote: "Note: Unverified accounts cannot make bookings. This link has a limited validity.",
    passResetPreview: "Password Recovery",
    hello: "Hello",
    passResetBody: "We received a request to reset the password for your Glamzo account. If this was you, click the button below to create a new password:",
    passResetBtn: "Reset Password",
    passResetNote: "If you didn't make this request, you can safely ignore this email. The link expires in 24 hours."
  },
  es: {
    bookingConfirmed: "¡Tu reserva está confirmada!",
    bookingConfirmedTitle: "Reserva Confirmada ✅",
    professional: "Profesional",
    service: "Servicio",
    date: "Fecha",
    time: "Hora",
    value: "Valor",
    reference: "Referencia",
    bookingFooter: "Puedes consultar los detalles y gestionar tu reserva en la app.",
    team: "El equipo de Glamzo",
    bookingCancelled: "Tu reserva fue cancelada",
    bookingCancelledTitle: "Reserva Cancelada ❌",
    reason: "Motivo",
    cancelledFooter: "Si tienes alguna duda, contacta al salón o programa un nuevo horario.",
    newBooking: "Nueva reserva en Glamzo",
    newBookingTitle: "¡Nueva Reserva Recibida! 🎉",
    estimatedValue: "Valor Estimado",
    newBookingFooter: "Consulta tu agenda en la plataforma para más detalles.",
    subActiveTitle: "Suscripción Activa 🚀",
    activation: "Activación",
    nextBilling: "Próximo Cobro",
    subActiveFooter: "Ya tienes acceso inmediato a todas las funciones avanzadas de gestión y marketing.",
    openDashboard: "Abrir Dashboard PRO",
    invoiceAvailable: "Acceso a tu Factura",
    invoiceBody: "El pago de tu suscripción se ha procesado con éxito. La factura ya está disponible.",
    invoiceNo: "Nº Factura",
    amountPaid: "Valor Pagado",
    downloadInvoice: "Descargar Factura",
    paymentFailed: "Método de Pago Rechazado ⚠️",
    updatePayment: "Actualizar Pago",
    welcomeStaff: "¡Bienvenido al equipo de ",
    staffBody: "Tu cuenta fue creada con éxito. Puedes acceder a tu panel de empleado en Glamzo usando las siguientes credenciales:",
    email: "Email",
    password: "Password",
    ignoreEmail: "Si no esperabas este email, puedes ignorarlo.",
    anyone: "Cualquiera",
    accessDashboard: "Acceder al Panel",
    verificationCode: "Tu código de verificación",
    welcome: "Bienvenido(a),",
    thanksForRegistering: "Gracias por registrarte en Glamzo. Para garantizar la seguridad de tu cuenta y continuar con el registro, ingresa el siguiente código de verificación:",
    validCode: "Este código solo es válido para el proceso de registro actual.",
    confirmEmailPreview: "Confirma tu email en Glamzo",
    confirmEmailBody: "Gracias por registrarte en Glamzo. Para garantizar la seguridad de tu cuenta y desbloquear todas las funciones, necesitamos que confirmes tu dirección de correo electrónico.",
    confirmEmailBtn: "Confirmar Email",
    confirmEmailNote: "Nota: Las cuentas no verificadas no pueden hacer reservas. Este enlace tiene una validez limitada.",
    passResetPreview: "Recuperación de Contraseña",
    hello: "Hola",
    passResetBody: "Recibimos una solicitud para restablecer la contraseña de tu cuenta de Glamzo. Si fuiste tú, haz clic en el botón de abajo para crear una nueva contraseña:",
    passResetBtn: "Restablecer Contraseña",
    passResetNote: "Si no hiciste esta solicitud, puedes ignorar este correo de forma segura. El enlace expira en 24 horas."
  },
  fr: {
    bookingConfirmed: "Votre réservation est confirmée !",
    bookingConfirmedTitle: "Réservation Confirmée ✅",
    professional: "Professionnel",
    service: "Service",
    date: "Date",
    time: "Heure",
    value: "Prix",
    reference: "Référence",
    bookingFooter: "Vous pouvez consulter les détails et gérer votre réservation dans l'application.",
    team: "L'équipe Glamzo",
    bookingCancelled: "Votre réservation a été annulée",
    bookingCancelledTitle: "Réservation Annulée ❌",
    reason: "Motif",
    cancelledFooter: "Si vous avez des questions, contactez le salon ou programmez un nouvel horaire.",
    newBooking: "Nouvelle réservation sur Glamzo",
    newBookingTitle: "Nouvelle Réservation Reçue ! 🎉",
    estimatedValue: "Prix Estimé",
    newBookingFooter: "Consultez votre agenda sur la plateforme pour plus de détails.",
    subActiveTitle: "Abonnement Actif 🚀",
    activation: "Activation",
    nextBilling: "Prochaine Facturation",
    subActiveFooter: "Vous avez désormais un accès immédiat à toutes les fonctionnalités avancées de gestion et de marketing.",
    openDashboard: "Ouvrir le Tableau de Bord PRO",
    invoiceAvailable: "Accès à votre Facture",
    invoiceBody: "Le paiement de votre abonnement a été traité avec succès. La facture est désormais disponible.",
    invoiceNo: "Nº Facture",
    amountPaid: "Montant Payé",
    downloadInvoice: "Télécharger la Facture",
    paymentFailed: "Moyen de Paiement Refusé ⚠️",
    updatePayment: "Mettre à jour le Paiement",
    welcomeStaff: "Bienvenue dans l'équipe de ",
    staffBody: "Votre compte a été créé avec succès. Vous pouvez accéder à votre tableau de bord d'employé sur Glamzo avec les identifiants suivants :",
    email: "Email",
    password: "Mot de passe",
    ignoreEmail: "Si vous n'attendiez pas cet e-mail, vous pouvez l'ignorer.",
    anyone: "N'importe qui",
    accessDashboard: "Accéder au Tableau de Bord",
    verificationCode: "Votre code de vérification",
    welcome: "Bienvenue,",
    thanksForRegistering: "Merci de vous être inscrit sur Glamzo. Pour garantir la sécurité de votre compte et poursuivre l'inscription, veuillez entrer le code de vérification suivant :",
    validCode: "Ce code n'est valable que pour le processus d'inscription actuel.",
    confirmEmailPreview: "Confirmez votre e-mail sur Glamzo",
    confirmEmailBody: "Merci de vous être inscrit sur Glamzo. Pour garantir la sécurité de votre compte et débloquer toutes les fonctionnalités, nous avons besoin que vous confirmiez votre adresse e-mail.",
    confirmEmailBtn: "Confirmer l'e-mail",
    confirmEmailNote: "Remarque : Les comptes non vérifiés ne peuvent pas effectuer de réservations. Ce lien a une validité limitée.",
    passResetPreview: "Récupération de mot de passe",
    hello: "Bonjour",
    passResetBody: "Nous avons reçu une demande de réinitialisation du mot de passe de votre compte Glamzo. Si c'est vous, cliquez sur le bouton ci-dessous pour créer un nouveau mot de passe :",
    passResetBtn: "Réinitialiser le mot de passe",
    passResetNote: "Si vous n'avez pas fait cette demande, vous pouvez ignorer cet e-mail en toute sécurité. Le lien expire dans 24 heures."
  }
};\n`;

code = code.substring(0, tStart) + translationsCode + code.substring(tEnd);
fs.writeFileSync('src/emails/GlamzoTemplates.tsx', code);
