import { Business, Service, Review, BusinessHours } from "../types";

export const FALLBACK_BUSINESSES: Business[] = [
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f0",
    owner_id: "user-fallback-1",
    name: "Salão & Spa Premium",
    slug: "salao-spa-premium",
    description: "O mais exclusivo salão de beleza e spa de Lisboa. Oferecemos tratamentos capilares personalizados, manicure de luxo, massagens relaxantes e cuidados faciais avançados.",
    category: "Cabelo & Barbearia",
    phone: "+351 912 345 678",
    email: "lisboa.premium@glamzo.pt",
    district: "Lisboa",
    city: "Lisboa",
    address: "Avenida da Liberdade, 120, 2º Esq",
    postal_code: "1250-096",
    logo_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351912345678",
    instagram: "@salao_spa_premium",
    website: "https://glamzo.pt/salao-spa-premium",
    is_verified: true,
    is_promoted: true,
    is_premium: true,
    status: "active",
    latitude: 38.7223,
    longitude: -9.1393,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f1",
    owner_id: "user-fallback-2",
    name: "Barbearia Braga Moderna",
    slug: "barbearia-braga-moderna",
    description: "Cortes modernos, barbas desenhadas à navalha clássica, ambiente descontraído com cerveja artesanal e música ao vivo.",
    category: "Cabelo & Barbearia",
    phone: "+351 922 987 654",
    email: "braga.moderna@glamzo.pt",
    district: "Braga",
    city: "Braga",
    address: "Rua do Souto, 45",
    postal_code: "4700-329",
    logo_url: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351922987654",
    instagram: "@barbeariabragamoderna",
    website: "https://glamzo.pt/barbearia-braga-moderna",
    is_verified: true,
    is_promoted: false,
    is_premium: true,
    status: "active",
    latitude: 41.5454,
    longitude: -8.4265,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f2",
    owner_id: "user-fallback-3",
    name: "Estética & Beleza Bragança",
    slug: "estetica-beleza-braganca",
    description: "Tratamentos corporais de ponta, depilação a laser de última geração e limpezas faciais com produtos biológicos.",
    category: "Estética",
    phone: "+351 933 111 222",
    email: "estetica.braganca@glamzo.pt",
    district: "Bragança",
    city: "Bragança",
    address: "Avenida Sá Carneiro, 12",
    postal_code: "5300-252",
    logo_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351933111222",
    instagram: "@esteticabraganca",
    website: "https://glamzo.pt/estetica-beleza-braganca",
    is_verified: false,
    is_promoted: false,
    is_premium: false,
    status: "active",
    latitude: 41.8058,
    longitude: -6.7572,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f3",
    owner_id: "user-fallback-4",
    name: "Glam Lounge Porto",
    slug: "glam-lounge-porto",
    description: "Especialistas em unhas de gel, manicure russa, nail art personalizada e extensão de pestanas de alto nível no coração do Porto.",
    category: "Nails & Beauty",
    phone: "+351 915 222 333",
    email: "porto.lounge@glamzo.pt",
    district: "Porto",
    city: "Porto",
    address: "Rua de Santa Catarina, 410",
    postal_code: "4000-443",
    logo_url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351915222333",
    instagram: "@glamloungeporto",
    website: "https://glamzo.pt/glam-lounge-porto",
    is_verified: true,
    is_promoted: true,
    is_premium: true,
    status: "active",
    latitude: 41.1579,
    longitude: -8.6291,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f4",
    owner_id: "user-fallback-5",
    name: "Zen Spa Porto",
    slug: "zen-spa-porto",
    description: "Um oásis urbano de tranquilidade no Porto. Oferecemos massagens de pedras quentes, massagem desportiva, shiatsu e tratamentos termais exclusivos.",
    category: "Wellness",
    phone: "+351 925 333 444",
    email: "zenspaporto@glamzo.pt",
    district: "Porto",
    city: "Porto",
    address: "Avenida da Boavista, 1850",
    postal_code: "4100-112",
    logo_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351925333444",
    instagram: "@zenspaporto",
    website: "https://glamzo.pt/zen-spa-porto",
    is_verified: true,
    is_promoted: false,
    is_premium: true,
    status: "active",
    latitude: 41.1610,
    longitude: -8.6415,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f5",
    owner_id: "user-fallback-6",
    name: "Corte Perfeito Porto",
    slug: "corte-perfeito-porto",
    description: "Cabeleireiro conceituado especializado em cortes femininos, balayage, Madeixas e alisamentos orgânicos de altíssima qualidade no Porto.",
    category: "Cabelo & Barbearia",
    phone: "+351 936 444 555",
    email: "corteperfeitoporto@glamzo.pt",
    district: "Porto",
    city: "Porto",
    address: "Rua do Almada, 180",
    postal_code: "4050-031",
    logo_url: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351936444555",
    instagram: "@corteperfeitoporto",
    website: "https://glamzo.pt/corte-perfeito-porto",
    is_verified: false,
    is_promoted: true,
    is_premium: false,
    status: "active",
    latitude: 41.1495,
    longitude: -8.6130,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f6",
    owner_id: "user-fallback-7",
    name: "Estúdio Unhas de Ouro Faro",
    slug: "estudio-unhas-faro",
    description: "O melhor espaço para manicure e pedicure do Algarve, localizado na baixa de Faro. Oferecemos gelinho, verniz de gel e tratamentos spa de mãos.",
    category: "Nails & Beauty",
    phone: "+351 917 555 666",
    email: "unhasfaro@glamzo.pt",
    district: "Faro",
    city: "Faro",
    address: "Rua de Santo António, 14",
    postal_code: "8000-283",
    logo_url: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351917555666",
    instagram: "@unhasdeourofaro",
    website: "https://glamzo.pt/estudio-unhas-faro",
    is_verified: true,
    is_promoted: false,
    is_premium: false,
    status: "active",
    latitude: 37.0179,
    longitude: -7.9308,
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f7",
    owner_id: "user-fallback-8",
    name: "Estilo & Charme Coimbra",
    slug: "cabeleireiro-coimbra",
    description: "Estilo moderno e sofisticação no centro histórico de Coimbra. Cabeleireiro unissexo, madeixas, rituais Kérastase e design de sobrancelhas.",
    category: "Cabelo & Barbearia",
    phone: "+351 928 666 777",
    email: "estilocombria@glamzo.pt",
    district: "Coimbra",
    city: "Coimbra",
    address: "Praça da República, 8",
    postal_code: "3000-343",
    logo_url: "https://images.unsplash.com/photo-1595475243681-30a2219b5b3a?auto=format&fit=crop&q=80&w=150",
    cover_url: "https://images.unsplash.com/photo-1595475243681-30a2219b5b3a?auto=format&fit=crop&q=80&w=800",
    whatsapp: "+351928666777",
    instagram: "@estilocharme_coimbra",
    website: "https://glamzo.pt/cabeleireiro-coimbra",
    is_verified: true,
    is_promoted: false,
    is_premium: true,
    status: "active",
    latitude: 40.2033,
    longitude: -8.4103,
    created_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const FALLBACK_SERVICES: Service[] = [
  {
    id: "s1",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f0",
    category_id: "cat-1",
    name: "Corte de Cabelo Feminino & Brushing",
    description: "Corte personalizado de acordo com o visagismo, com lavagem relaxante, máscara de hidratação profunda e brushing incluído.",
    price: 45.00,
    duration_minutes: 60,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s2",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f0",
    category_id: "cat-1",
    name: "Manicure Clássica com Verniz de Gel",
    description: "Limpeza de cutículas, limagem e aplicação de base endurecedora e verniz de gel com durabilidade até 4 semanas.",
    price: 22.00,
    duration_minutes: 45,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s3",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f0",
    category_id: "cat-1",
    name: "Massagem de Assinatura Zen 60 min",
    description: "Massagem de corpo inteiro com óleos essenciais aquecidos e pedras vulcânicas para um relaxamento muscular profundo e alívio do stress.",
    price: 60.00,
    duration_minutes: 60,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s4",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f1",
    category_id: "cat-2",
    name: "Corte de Cabelo Degradê",
    description: "Corte com máquina e tesoura de alta precisão, finalizado com cera premium e tónico refrescante.",
    price: 15.00,
    duration_minutes: 30,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s5",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f1",
    category_id: "cat-2",
    name: "Ritual Barba Toalha Quente",
    description: "Barba completa aparada com óleos suavizantes, hidratação profunda e aplicação de toalha quente aromática relaxante.",
    price: 12.00,
    duration_minutes: 30,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s6",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f2",
    category_id: "cat-3",
    name: "Depilação a Laser Meias Pernas",
    description: "Sessão de depilação a laser de díodo de última geração, indolor e altamente eficaz para eliminação permanente de pelos.",
    price: 35.00,
    duration_minutes: 30,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s7",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f3",
    category_id: "cat-4",
    name: "Unhas de Gel com Extensão",
    description: "Aplicação profissional de unhas de gel com moldes para extensão, limagem profissional e aplicação de cor à escolha.",
    price: 35.00,
    duration_minutes: 90,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s8",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f3",
    category_id: "cat-4",
    name: "Design de Sobrancelhas com Henna",
    description: "Mapeamento das sobrancelhas segundo o rosto, depilação a linha e aplicação de henna para um efeito sombreado natural.",
    price: 18.00,
    duration_minutes: 40,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s9",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f4",
    category_id: "cat-5",
    name: "Massagem Terapêutica de Costas",
    description: "Massagem localizada de alta pressão focada no alívio de tensões, contraturas acumuladas na cervical, dorsais e lombares.",
    price: 30.00,
    duration_minutes: 30,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  },
  {
    id: "s10",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f5",
    category_id: "cat-1",
    name: "Balayage Couture & Tratamento",
    description: "Trabalho de madeixas artísticas à mão livre com descoloração protetora e hidratação profunda reconstrutora.",
    price: 85.00,
    duration_minutes: 150,
    image_url: null,
    is_active: true,
    created_at: new Date().toISOString()
  }
];

export const FALLBACK_REVIEWS: Review[] = [
  {
    id: "r1",
    booking_id: "book-fallback-r1",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f0",
    customer_id: "cust-1",
    customer_name: "Ana Silva",
    rating: 5,
    comment: "Melhor salão de Lisboa! O atendimento é impecável e o espaço é super luxuoso. Adorei o corte de cabelo e o spa.",
    service_id: "s1",
    service_name: "Corte de Cabelo Premium",
    created_at: new Date().toISOString()
  },
  {
    id: "r2",
    booking_id: "book-fallback-r2",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f0",
    customer_id: "cust-2",
    customer_name: "Mariana Costa",
    rating: 5,
    comment: "Manicure russa espetacular. Super cuidadosa, recomendo muito este salão premium.",
    service_id: "s2",
    service_name: "Manicure de Gel Luxo",
    created_at: new Date().toISOString()
  },
  {
    id: "r3",
    booking_id: "book-fallback-r3",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f1",
    customer_id: "cust-3",
    customer_name: "Pedro Santos",
    rating: 5,
    comment: "Atendimento incrível de toda a equipa! Excelente corte degradê e cerveja fantástica.",
    service_id: "s4",
    service_name: "Corte Moderno & Navalha",
    created_at: new Date().toISOString()
  },
  {
    id: "r4",
    booking_id: "book-fallback-r4",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f3",
    customer_id: "cust-4",
    customer_name: "Sofia Martins",
    rating: 5,
    comment: "Design de sobrancelha impecável, a Henna ficou na cor exata. Recomendo muito o Glam Lounge!",
    service_id: "s6",
    service_name: "Design de Sobrancelha com Linha",
    created_at: new Date().toISOString()
  },
  {
    id: "r5",
    booking_id: "book-fallback-r5",
    business_id: "f1b5eeb5-b32d-4738-b93f-c0a8df2435f4",
    customer_id: "cust-5",
    customer_name: "Rui Oliveira",
    rating: 5,
    comment: "A massagem desportiva salvou as minhas costas! Super profissional e experiente.",
    service_id: "s8",
    service_name: "Massagem Desportiva Pro",
    created_at: new Date().toISOString()
  }
];

export const FALLBACK_HOURS: BusinessHours[] = [];
// Populate standard open days for all fallback businesses
FALLBACK_BUSINESSES.forEach(b => {
  for (let i = 1; i <= 6; i++) {
    FALLBACK_HOURS.push({
      id: `h-${b.id}-${i}`,
      business_id: b.id,
      weekday: i,
      open_time: "09:00",
      close_time: "19:00",
      is_closed: false
    });
  }
  // Sunday is closed
  FALLBACK_HOURS.push({
    id: `h-${b.id}-0`,
    business_id: b.id,
    weekday: 0,
    open_time: "00:00",
    close_time: "00:00",
    is_closed: true
  });
});
